### ISSUE TITLE
AttributeError: 'pyngp.Nerf' object has no attribute 'sharpness_threshold'

### ISSUE THREAD

**Issue by flybiubiu** [NVlabs/ParallelInversion#1]
Nice Work!But I have a problem:
Loss type: L2
----------------------------------------------------
Scene: lego
*************************************
IDX: 0
delta_phi: 8.140797565872028
delta_theta: 10.820093141330617
delta_psi: -10.48089103181714
delta_tx: 0.24528741576016583
delta_ty: 0.09526715962921517
delta_tz: 0.22406161059494684
12:25:40 SUCCESS  Initialized CUDA 11.3. Active GPU is #0: NVIDIA TITAN X (Pascal) [61]
Traceback (most recent call last):
  File "/media/4t/projects/ParallelInversion/scripts/exp_nerf_synthetic.py", line 72, in <module>
    shell(args)
  File "/media/4t/projects/ParallelInversion/scripts/exp_nerf_synthetic.py", line 46, in shell
    run_pose_refinement.run_exp(args)
  File "/media/4t/projects/ParallelInversion/scripts/run_pose_refinement.py", line 1211, in run_exp
    error_rotation, error_translation, meta_optimization = main(args)
  File "/media/4t/projects/ParallelInversion/scripts/run_pose_refinement.py", line 812, in main
    init_training(meta_training, args, WITH_TRAINING=True)
  File "/media/4t/projects/ParallelInversion/scripts/run_pose_refinement.py", line 614, in init_training
    testbed.nerf.sharpness_threshold = float(args.sharpness_threshold)
AttributeError: 'pyngp.Nerf' object has no attribute 'sharpness_threshold'

Thx!

**Comment by Uio96** [comment]
Thanks for the interest in our work. 

Could you double-check the installation? Make sure you follow the instructions (Can you play around with run_debug.py file?).  I did not encounter your issue on my end.

**Comment by chunzhi666** [comment]
> ## Nice Work!But I have a problem:
> Loss type: L2
> 
> Scene: lego
> 
> IDX: 0 delta_phi: 8.140797565872028 delta_theta: 10.820093141330617 delta_psi: -10.48089103181714 delta_tx: 0.24528741576016583 delta_ty: 0.09526715962921517 delta_tz: 0.22406161059494684 12:25:40 SUCCESS Initialized CUDA 11.3. Active GPU is #0: NVIDIA TITAN X (Pascal) [61] Traceback (most recent call last): File "/media/4t/projects/ParallelInversion/scripts/exp_nerf_synthetic.py", line 72, in shell(args) File "/media/4t/projects/ParallelInversion/scripts/exp_nerf_synthetic.py", line 46, in shell run_pose_refinement.run_exp(args) File "/media/4t/projects/ParallelInversion/scripts/run_pose_refinement.py", line 1211, in run_exp error_rotation, error_translation, meta_optimization = main(args) File "/media/4t/projects/ParallelInversion/scripts/run_pose_refinement.py", line 812, in main init_training(meta_training, args, WITH_TRAINING=True) File "/media/4t/projects/ParallelInversion/scripts/run_pose_refinement.py", line 614, in init_training testbed.nerf.sharpness_threshold = float(args.sharpness_threshold) AttributeError: 'pyngp.Nerf' object has no attribute 'sharpness_threshold'
> 
> Thx!

Hi, did you just follow the instructions and successfully finish the installation process? I have some problems when compiling with cmake, and would like to know if you had met any problem or compilation errors before. Thx!

**Comment by flybiubiu** [comment]
这个是较早版本的ngp的运行结果，现在重新拉code会报cpu buffer的错误。
