### ISSUE TITLE
RuntimeError: Can't set params because CPU buffer has the wrong size.

### ISSUE THREAD

**Issue by YosinLiu** [NVlabs/ParallelInversion#4]
Hi, thank you so much for the impressive work and sharing the codes!
I have tried the installation steps according to the instructions, but I encountered some problems and I sincerely hope to get your advice on them.
After I run the "python exp_nerf_synthetic.py --config config/exp/exp_nerf_synthetic.yaml", The logs are here:
sen@sen-B460MAORUSPRO:~/Desktop/ParallelInversion/scripts$ python exp_nerf_synthetic.py --config config/exp/exp_nerf_synthetic.yaml
Loss type: L2
----------------------------------------------------
Scene: lego
*************************************
IDX: 0
delta_phi: 8.140797565872028
delta_theta: 10.820093141330617
delta_psi: -10.48089103181714
delta_tx: 0.24528741576016583
delta_ty: 0.09526715962921517
delta_tz: 0.22406161059494684
Target view name /home/sen/Desktop/ParallelInversion/data/nerf/nerf_synthetic/lego/./test/r_47.png
Matched pose ./test/r_47
Start pose is initialized from the ground truth
Start pose is initialized from the noisy ground truth
delta translation has been re-scaled by the scale_ratio_test: 1.0
No noise added to the observed image
07:38:02 INFO     Loading NeRF dataset from
07:38:02 INFO       /home/sen/Desktop/ParallelInversion/data/nerf/nerf_synthetic/lego/transforms_temp.json
07:38:02 SUCCESS  Loaded 1 images
07:38:02 INFO       cam_aabb=[min=[0.364406,-0.603703,1.23287], max=[0.364406,-0.603703,1.23287]]
07:38:02 INFO     Loading network config from: /home/sen/Desktop/ParallelInversion/data/nerf/nerf_synthetic/lego/model_L2.msgpack
07:38:03 INFO     GridEncoding:  Nmin=16 b=1.38191 F=2 T=2^19 L=16
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
07:38:03 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
07:38:03 INFO     Color model:   3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
07:38:03 INFO       total_encoding_params=12196240 total_network_params=9728
Traceback (most recent call last):
  File "/home/sen/Desktop/ParallelInversion/scripts/exp_nerf_synthetic.py", line 72, in <module>
    shell(args)
  File "/home/sen/Desktop/ParallelInversion/scripts/exp_nerf_synthetic.py", line 46, in shell
    run_pose_refinement.run_exp(args)
  File "/home/sen/Desktop/ParallelInversion/scripts/run_pose_refinement.py", line 1210, in run_exp
    error_rotation, error_translation, meta_optimization = main(args)
  File "/home/sen/Desktop/ParallelInversion/scripts/run_pose_refinement.py", line 830, in main
    testbed.load_snapshot(meta_training["scene_model"])
RuntimeError: Can't set params because CPU buffer has the wrong size.

**Comment by Uio96** [comment]
Thanks for the interest in our work. The error seems to be an issue with InstantNGP, which I have not encountered myself. This discussion might be helpful https://github.com/NVlabs/instant-ngp/discussions/502
